baseURL = 'https://scattered-ai.github.io/'
languageCode = 'en-us'
title = 'Scattered AI'


disablePathToLower = true
enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'